### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [Licoy/A-Joke#4]
Hi @Licoy . I'm a graphic designer and an open source enthusiast. I've designed a logo/icon for you and it's free. If you have an idea please share with me, is there anything you want to change please let me know. Best Regard. Mirza Zulfan
![joke](https://user-images.githubusercontent.com/36124339/44641927-e5105500-a9f3-11e8-9b6a-5a06c302d904.png)

**Comment by Licoy** [comment]
@mirzazulfan 

Great design, thank you very much for your design, and I am very willing to adopt the LOGO you designed for us.

In addition, here is a LOGO designed by us. You can refer to it:

![](https://www.licoy.cn/wp-content/uploads/2018/07/ajoke.png)

**Comment by Licoy** [comment]
@mirzazulfan 

Great design, thank you very much for your design, and I am very willing to adopt the LOGO you designed for us.

But can you consider changing the purple background to a transparent background logo image?

**Comment by mirzazulfan** [comment]
Hi @Licoy .. I am glad you liked :+1: . should i create a pr ?
![transparant](https://user-images.githubusercontent.com/36124339/44826707-46296a00-ac3a-11e8-9ecc-6d0027336af9.png)

**Comment by Licoy** [comment]
@mirzazulfan Yes, you can do this. Thanks

**Comment by mirzazulfan** [comment]
Hi @Licoy ,, I've created a pr, please check #5 . Thank you.
Best Regard.

**Comment by Licoy** [comment]
@mirzazulfan Merged, thanks
